name: build release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Install cc65
        run: sudo apt install -y cc65

      - name: Build the ROM
        run: ./build.sh
